<a href="https://www.kaggle.com/code/shreya1003/numpy-for-beginners?scriptVersionId=198781359" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [1]:
import numpy as np
arr = np.array([1,2,3]) #Created a one dimensional array
arr

array([1, 2, 3])

In [2]:
# To check the dimension of an array
arr.ndim

1

In [3]:
#Creating a 2d array
arr1 = np.array([[1,2,3],[4,5,6]])
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
arr1.ndim

2

In [5]:
#Creating a 3d array
a = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
a

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [6]:
a.ndim

3

In [7]:
#Access an array element
arr = np.array([1,2,3])
arr[0]

1

In [8]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr1[0][2]

3

In [9]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr1[1][1]

5

In [10]:
a = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
a[0][0][2]

3

In [11]:
a[0][1][2]

6

In [12]:
a[0][2][2]

9

In [13]:
#Total number of rows and columns
a.shape

(1, 3, 3)

In [14]:
arr1.shape

(2, 3)

In [15]:
#flatten an array
a.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
a.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
#Create an array of 10 elements using arange() function
newArr = np.arange(10)
newArr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
#Create an array of zeros
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [19]:
#Create an array of ones
np.ones(5)

array([1., 1., 1., 1., 1.])

In [20]:
#Create a empty array of 5 size
np.empty(5)

array([1., 1., 1., 1., 1.])

In [21]:
#Data type of an array
newarr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
newarr.dtype

dtype('int64')

In [22]:
#Change the dtype/data type of an array
newarr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9],dtype = 'f') # f means float 
newarr.dtype
#You can use 'S' --> string
#'i'--> integer 

dtype('float32')

In [23]:
#Reshape an array
Arr = np.arange(24)
Arr.reshape(6,4) #means It will reshape the array which has 6rows 4cols

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [24]:
#sort an array
sort_arr = ([8,3,77,39,2,5,44])
np.sort(sort_arr)

array([ 2,  3,  5,  8, 39, 44, 77])

In [25]:
#sort an array by index
sort_arr = ([8,3,77,39,2,5,44])
np.argsort(sort_arr)

array([4, 1, 5, 0, 3, 6, 2])

In [26]:
#Find max element from an array
max_arr = ([8,3,77,39,2,5,44])
np.max(max_arr) #It will return the element

77

In [27]:
np.argmax(max_arr) #It will return the index of the element

2

In [28]:
min_arr = ([8,3,77,39,2,5,44])
np.min(min_arr) #It will return the element

2

In [29]:
np.argmin(min_arr) #It will return the index of the element

4

In [30]:
#Sort an array using axis
arr = np.array([[1, 5, 1, 4, 3, 4, 4],[9, 4, 0, 4, 0, 2, 1]])
np.sort(arr,axis = 0) #It will sort the cols (axis = 0 ---> cols,axis=1 --> rows)

array([[1, 4, 0, 4, 0, 2, 1],
       [9, 5, 1, 4, 3, 4, 4]])

In [31]:
arr = np.array([[1, 5, 1, 4, 3, 4, 4],[9, 4, 0, 4, 0, 2, 1]])
np.sort(arr,axis = 1)

array([[1, 1, 3, 4, 4, 4, 5],
       [0, 0, 1, 2, 4, 4, 9]])

In [32]:
#Create a 3*3 identity matrix
id_matrix = np.eye(3)
id_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [33]:
#Create a linearly spaced array
linspace_array = np.linspace(0,20,num=10)# The array has total 10 elements which are linearly spaced from 0 to 20
linspace_array

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [34]:
#Concatenate two arrays
arr1 = np.array([1,8,3,7,66,0,26,78,99])
arr2 = np.array([1,8,99])
np.concatenate((arr1,arr2))

array([ 1,  8,  3,  7, 66,  0, 26, 78, 99,  1,  8, 99])

In [35]:
# print those element where element > 1
arr1 = np.array([1,8,3,7,66,0,26,78,99])
np.argwhere(arr1>1)

array([[1],
       [2],
       [3],
       [4],
       [6],
       [7],
       [8]])

In [36]:
# Count elements which are non zero
arr = np.array([1,2,3,0,4,5,6,0,0,0])
np.count_nonzero(arr)

6

In [37]:
# Add a new axis
arr = np.array([1,2,3,0,4,5,6,0,0,0])
arr.shape # This array has only 10 rows

(10,)

In [38]:
arr2 = arr[np.newaxis,:]
arr2.shape 

(1, 10)

In [39]:
#Slicing
arr1 = np.array([1,8,3,7,66,0,26,78,99])
arr1[2:8]

array([ 3,  7, 66,  0, 26, 78])

In [40]:
#Split the array
h_arr = np.array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])
np.hsplit(h_arr,3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [41]:
#Create an array with random values
Z = np.random.random((3,3))
Z

array([[0.43432159, 0.95498585, 0.64890651],
       [0.88119992, 0.88134218, 0.38176159],
       [0.2002433 , 0.6618674 , 0.31530027]])

In [42]:
#Mean of the array
Z.mean()

0.5955476231097395

In [43]:
#Find unique value from an array
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])
np.unique(a)

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [44]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])
np.unique(a,return_index = True) 

(array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20]),
 array([ 0,  2,  3,  4,  5,  6,  7, 12, 13, 14]))

In [45]:
np.unique(a,return_counts = True) 

(array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20]),
 array([3, 2, 2, 2, 1, 1, 1, 1, 1, 1]))

In [46]:
# Transpose an array (Transpose means row --> col,col --> row)
transposed_array = np.array([[1, 1, 3, 4, 4, 4, 5],
       [0, 0, 1, 2, 4, 4, 9]])
transposed_array.transpose()

array([[1, 0],
       [1, 0],
       [3, 1],
       [4, 2],
       [4, 4],
       [4, 4],
       [5, 9]])

In [47]:
#Reverse an array
rev_arr = np.array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])
np.flip(rev_arr)

array([20, 19, 18, 17, 16, 15, 14, 13, 12, 11])

In [48]:
#Now most important
#Why Numpy is better than Python List

#3 benefits of Numpy array
#1. Less Memory
#2. Fast
#3. Convinient

In [49]:
import time
import sys
l = range(1000)
print(sys.getsizeof(l)*len(l))

48000


In [50]:
arr = np.arange(1000)
print(arr.size*arr.itemsize)

8000


In [51]:
l1  = range(1000000)
l2  = range(1000000)
start = time.time()
result = [(x+y) for x,y in zip(l1,l2)]
print("List takes time: ",(time.time()-start)*1000)

List takes time:  181.2891960144043


In [52]:
arr1  = np.arange(1000000)
arr2  = np.arange(1000000)
startArray = time.time()
resultArray = arr1 + arr2
print("Numpy array takes time: ",(time.time()-startArray)*1000)

Numpy array takes time:  4.166603088378906
